/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#111c2d",
        "primary": "#2563eb",
        "primary-hover": "#1d4ed8",
        "primary-surface": "#eff6ff",
        "surface-dim": "#cfdaf2",
        "surface-tint": "#0053db",
        "surface-container-high": "#dee8ff",
        "on-secondary-fixed": "#23005c",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#ecf1ff",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#d8e3fb",
        "on-surface-variant": "#434655",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b4c5ff",
        "secondary": "#6b38d4",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#005236",
        "surface": "#f9f9ff",
        "background": "#f9f9ff",
        "surface-container": "#e7eeff",
        "on-primary-fixed": "#00174b",
        "inverse-surface": "#263143",
        "on-tertiary-fixed": "#002113",
        "primary-fixed": "#dbe1ff",
        "on-secondary-fixed-variant": "#5516be",
        "on-tertiary-container": "#bdffdb",
        "outline-variant": "#c3c6d7",
        "tertiary": "#006242",
        "surface-bright": "#f9f9ff",
        "error-container": "#ffdad6",
        "on-secondary-container": "#fffbff",
        "primary-container": "#2563eb",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed-dim": "#d0bcff",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-low": "#f0f3ff",
        "on-primary": "#ffffff",
        "inverse-primary": "#b4c5ff",
        "on-primary-container": "#eeefff",
        "tertiary-fixed-dim": "#4edea3",
        "error": "#ef4444",
        "on-background": "#111c2d",
        "secondary-fixed": "#e9ddff",
        "outline": "#737686",
        "tertiary-container": "#007d55",
        "surface-variant": "#d8e3fb",
        "secondary-container": "#8455ef"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "container-max": "1200px",
        "margin-mobile": "16px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "gutter": "24px",
        "stack-sm": "12px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "system-ui", "sans-serif"],
        "display": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "section-header": ["'Plus Jakarta Sans'", "sans-serif"],
        "card-title": ["'Plus Jakarta Sans'", "sans-serif"],
        "body": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "caption": ["'Plus Jakarta Sans'", "sans-serif"]
      },
      fontSize: {
        "display": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "section-header": ["20px", { lineHeight: "1.4", fontWeight: "700" }],
        "card-title": ["16px", { lineHeight: "1.5", fontWeight: "600" }],
        "body": ["15px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["13px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "500" }],
        "caption": ["12px", { lineHeight: "1.4", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
